Language/Python/Project/django/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^index/$', views.index1),
    url(r'^index.html/$', views.index0),
    url(r'^(\d+)/$', views.detailnum),
    url(r'^(\d+)/(\d+)/$', views.detailtwonums),
    url(r'^grades/$', views.grades),
    url(r'^students/$', views.students),
    url(r'^grades/(\d+)/$', views.gradeStudents),
    url(r'^addstudent1/$', views.addStudent1),
    url(r'^addstudent2/$', views.addStudent2),
    url(r'^students/(\d+)/$', views.stupage),
    url(r'^showrequest/$', views.showrequest),
    url(r'^showresponse/$', views.showresponse),
    url(r'^get1/$', views.get1),
    url(r'^get2/$', views.get2),
    url(r'^showregister/$', views.showregister),
    url(r'^showregister/register/$', views.register),
    url(r'^cookieset/$', views.cookieset),
    url(r'^cookieget/$', views.cookieget),
    url(r'^redirect1/$', views.redirect1),
    url(r'^redirect2/$', views.redirect2),
    url(r'^main/$', views.main),
    url(r'^login/$', views.login),
    url(r'^login/showmain/$', views.showmain),
    url(r'^quit/$', views.quit),
    url(r'^bad/$', views.bad, name="bad"),
    url(r'^good/$', views.good, name="good"),
    url(r'^mymain_base01/$', views.mymain_base01),
    url(r'^test/$', views.test),
    url(r'^postfile/$', views.postfile),
    url(r'^showinfo/$', views.showinfo),
    url(r'^upfile/$', views.upfile),
    url(r'^savefile/$', views.savefile),
    url(r'^studentspage/(\d+)/$', views.studentspage),
    url(r'^studentsajax/$', views.studentsajax),
    url(r'^studentsinfo/$', views.studentsinfo),
    url(r'^fuwenben/$', views.fuwenben),
    url(r'^celery/$', views.celery),
]

Language/Python/Project/django/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^mlin/', include('myapp.urls')),
    url(r'^', include('myapp.urls', namespace="myapp"))
]

Language/Python/Project/django/myapp/models.py
from django.db import models

# Create your models here.

class Grades(models.Model):
    gname    = models.CharField(max_length=20)
    gdate    = models.DateTimeField()
    ggirlnum = models.IntegerField()
    gboynum  = models.IntegerField()
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        # 结果不方便查看，只是为了演示
        # return "%s-%s-%d"%(self.gname, self.ggirlnum, self.gboynum)
        return self.gname

    class Meta:
        db_table="grades"

class StudentsManager(models.Manager):
    def get_queryset(self):
        return super(StudentsManager,self).get_queryset().filter(isDelete=False)

    def createStudent2(self, name, age, gender, content, grade, lastT, createT, isD=False):
        stu = self.model()
        stu.sname = name
        stu.sage = age
        stu.sgender = gender
        stu.scontent = content
        stu.sgrade = grade
        stu.lastTime = lastT
        stu.createTime = createT
        return stu

class Students(models.Model):
    # 自定义管理器
    stuObj1 = models.Manager()
    stuObj2 = StudentsManager()

    sname    = models.CharField(max_length=20)
    sgender  = models.BooleanField(default=True)
    sage     = models.IntegerField()
    scontent = models.CharField(max_length=100)
    isDelete = models.BooleanField(default=False)
    # 关联外键
    sgrade   = models.ForeignKey("Grades")

    def __str__(self):
        return self.sname

    lastTime = models.DateTimeField(auto_now=True)
    createTime = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table="students"
        ordering=['id']

    # 定义一个类方法来创建对象
    @classmethod
    def createStudent1(cls, name, age, gender, content, grade, lastT, createT, isD=False):
        stu = cls(sname=name, sage=age, sgender=gender, scontent=content, sgrade=grade, lastTime=lastT,
                createTime=createT, isDelete=isD)
        return stu

from tinymce.models import HTMLField
class Text(models.Model):
    str = HTMLField()

Language/Python/Project/django/myapp/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse,HttpResponseRedirect
def index(request):
    return HttpResponse("Hello World, This is mlin.")

def index0(request):
    return HttpResponseRedirect("/")

from django.shortcuts import redirect
def index1(request):
    return redirect("/")

def detailnum(request, num):
    return HttpResponse("detail-%s"%num)

def detailtwonums(request, num1, num2):
    return HttpResponse("detail-%s-%s"%(num1, num2))

from .models import Grades
def grades(request):
    # 去模板里取数据
    gradesList = Grades.objects.all()
    # 将数据传递给模板，模板在渲染页面，再将渲染好的页面传递回给浏览器
    # 传参数时，传的是一个字典，键是形参，值是实参
    return render(request, 'myapp/grades.html', {"grades":gradesList})

from .models import Students
def students(request):
    studentsList = Students.stuObj1.all()
    return render(request, 'myapp/students.html', {"students":studentsList})

def stupage(request, page):
    # 每页显示5条数据
    page = int(page)
    studentsList = Students.stuObj1.all()[(page - 1) * 5:page * 5]
    return render(request, 'myapp/students.html', {"students":studentsList})

def gradeStudents(request,num):
    grade = Grades.objects.get(pk=num)
    studentsList = grade.students_set.all()
    return render(request, 'myapp/students.html', {"students":studentsList})

def addStudent1(request):
    grade = Grades.objects.get(pk=1)
    stu = Students.createStudent1("八神庵", 18, True, "我叫八神庵，我爱弹吉他。", grade,
            "2018-01-29", "2018-01-29")
    stu.save()
    return HttpResponse("创建了学生：八神庵。")

def addStudent2(request):
    grade = Grades.objects.get(pk=1)
    stu = Students.stuObj2.createStudent2("神乐千鹤", 18, False, "我是鹤", grade, "2018-01-30", "2018-01-30")
    stu.save()
    return HttpResponse("创建了学生：神乐千鹤。")

def showrequest(request):
    print(request.path)
    print(request.method)
    print(request.encoding)
    print(request.GET)
    print(request.POST)
    print(request.FILES)
    print(request.COOKIES)
    print(request.session)
    return HttpResponse("showrequest")

def showresponse(request):
    res = HttpResponse()
    res.content = b'good'
    print(res.content)
    print(res.charset)
    print(res.status_code)
    print(res.content-type)
    return res

def get1(request):
    a = request.GET.get('a')
    b = request.GET.get('b')
    c = request.GET['c']
    return HttpResponse(a + "===" + b + "===" + c)

def get2(request):
    a = request.GET.getlist('a')
    a1 = a[0]
    a2 = a[1]
    c = request.GET['c']
    return HttpResponse(a1 + "===" + a2 + "===" + c)

def showregister(request):
    return render(request, 'myapp/register.html')

def register(request):
    name = request.POST.get("name")
    gender = request.POST.get("gender")
    age = request.POST.get("age")
    hobby = request.POST.getlist("hobby")
    print(name)
    print(gender)
    print(age)
    print(hobby)
    return HttpResponse("register not open, infomation printed background.")

def cookieset(request):
    res = HttpResponse()
    cookie = res.set_cookie("mlin", "good man")
    return res

def cookieget(request):
    res = HttpResponse()
    cookie = request.COOKIES
    res.write("<h1>"+cookie["mlin"]+"</h1>")
    return res

from django.http import HttpResponseRedirect
def redirect1(request):
    return HttpResponseRedirect("/redirect2")

def redirect2(request):
    return HttpResponse("this is redirect2`s page.")

def main(request):
    # 取session
    username = request.session.get('uname', '游客')
    return render(request, "myapp/main.html", {'username':username})

def login(request):
    return render(request, "myapp/login.html")

def showmain(request):
    username = request.POST.get("username")
    # 存储session
    request.session['uname'] = username
    request.session.set_expiry(10)
    return redirect("/main")

from django.contrib.auth import logout
def quit(request):
    # 清除session
    logout(request)
    return redirect("/main")

def bad(request):
    return render(request, 'myapp/bad.html')

def good(request):
    return render(request, 'myapp/good.html')

def mymain_base01(request):
    return render(request, 'myapp/mymain_base01.html')

def test(request):
    return render(request, 'myapp/test.html', {"code":"<h1>this is code from view</h1>"})

def postfile(request):
    return render(request, 'myapp/postfile.html')

def showinfo(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    return render(request, 'myapp/showinfo.html', {"username":username,"password":password})

def upfile(request):
    return render(request, 'myapp/upfile.html')

import os
from django.conf import settings
def savefile(request):
    if request.method == "POST":
        file = request.FILES["file"]
        filePath = os.path.join(settings.MDEIA_ROOT, file.name)
        with open(filePath, 'wb') as fp:
            for info in file.chunks():
                fp.write(info)
        return HttpResponse("upload succesed!")
    else:
        return HttpResponse("upload failed!")

from .models import Students
from django.core.paginator import Paginator
def studentspage(request, pageid):
    allList = Students.stuObj1.all()
    paginator = Paginator(allList, 6)
    page = paginator.page(pageid)
    return render(request, 'myapp/studentspage.html', {"students":page})

def studentsajax(request):
    return render(request, 'myapp/studentsajax.html')

from django.http import JsonResponse
def studentsinfo(request):
    stus = Students.stuObj1.all()
    list = []
    for stu in stus:
        list.append([stu.sname, stu.sage, stu.sgender])
    return JsonResponse({"data":list})

def fuwenben(request):
    return render(request, 'myapp/fuwenben.html')

from .task import wait5s
def celery(request):
    wait5s.delay()
    return render(request, 'myapp/celery.html')

Language/Python/Project/django/templates/myapp/bad.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>BAD</title>
</head>
<body>
	<h1>BAD</h1></br>
	<a href="/good/">CHANGE</a></br>
	<a href="{% url 'myapp:good' %}">change</a>
</body>
</html>

Language/Python/Project/django/templates/myapp/good.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>GOOD</title>
</head>
<body>
    <h1>GOOD</h1></br>
	<a href="/myapp/bad/">CHANGE</a></br>
	<a href="{% url 'myapp:bad' %}">change</a>
</body>
</html>

Language/Python/Project/django/templates/myapp/grades.html
<!DOCTYPE html>
<html lang=en>
<head>
    <meta charset="UTF-8">
    <title>班级信息</title>
</head>
<body>
    <h1>班级信息列表</h1>
    <ul>
        <!--[python04, python05, python06]-->
        {%for grade in grades%}
        <li>
            <a href="{{grade.id}}">{{grade.gname}}</a>
        </li>
        {%endfor%}
    </ul>
</body>
</html>

Language/Python/Project/django/templates/myapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登录</title>
</head>
<body>
	<form action="showmain/" method="post">
		<input type="text" name="username"/><br />
		<input type="submit" value="登录"/>
	</form>
</body>
</html>

Language/Python/Project/django/templates/myapp/mybase01.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MYBASE01</title>
	<style>
		#header{
			width:100%;
			height:100px;
			background-color:red;
		}
		#footer{
			width:100%;
			height:100px;
			background-color:blue;
		}
	</style>
</head>
<body>
	<div id="header">header</div>
	<div id="main">
		{% block main %}
		{% endblock main %}
	</div>
	<div id="footer">footer</div>
</body>
</html>

Language/Python/Project/django/templates/myapp/mymain_base01.html
{% extends 'myapp/mybase01.html' %}

{% block main %}
	<h1>This is page mymain_mybase01</h1>
{% endblock main %}

Language/Python/Project/django/templates/myapp/postfile.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>POSTFILE</title>
</head>
<body>
	<form action="/showinfo/" method="post">
		{% csrf_token %}
		username: <input type="text" name="username"/>
		<hr/>
		password: <input type="password" name="password"/>
		<hr/>
		<input type="submit" value="LOGIN">
	</form>
</body>
</html>

Language/Python/Project/django/templates/myapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>注册</title>
</head>
<body>
	<form action="register/" method="post">
		姓名：<input type="text" name="name" value=""/>
		<hr/>
		性别：<input type="radio" name="gender" value="1"/>男<input type="radio" name="gender" value="0"/>女
		<hr/>
		年龄：<input type="text" name="age" value=""/>
		<hr/>
		爱好：<input type="checkbox" name="hobby" value="power"/>权利<input type="checkbox" name="hobby" value="money"/>金钱<input type="checkbox" name="hobby" value="freedom"/>自由
		<hr/>
		<input type="submit" value="注册"/>
	</form>
</body>
</html>

Language/Python/Project/django/templates/myapp/showinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>SHOWINFO</title>
</head>
<body>
	<h1>username: {{username}}</h1>
	<h1>password: {{password}}</h1>
</body>
</html>

Language/Python/Project/django/templates/myapp/students.html
<html lang=en>
<!DOCTYPE html>
<html lang=en>
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
</head>
<body>
    <h1>学生信息列表</h1>
    <table border="1">
        <tr>
            <th>NO.</th>
            <th>NAME</th>
            <th>AGE</th>
            <th>CONTENT</th>
        </tr>
        {%for student in students%}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{student.sname}}</td>
            <td>{{student.sage}}</td>
            <td>{{student.scontent}}</td>
        </tr>
        {%endfor%}
    </table>    
</body>
</html>

Language/Python/Project/django/templates/myapp/studentsajax.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>STUDENTSAJAX</title>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/style.css' %}"/>
	<script type="text/javascript" src="{% static 'myapp/js/jquery-3.1.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'myapp/js/mlin.js' %}"></script>
</head>
<body>
	<h1>STUDENTSAJAX</h1>
	<button id="btn">view student info</button>
</body>
</html>

Language/Python/Project/django/templates/myapp/template.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>TEMPLATE</title>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/style.css' %}"/>
	<script type="text/javascript" src="{% static 'myapp/js/jquery-3.1.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'myapp/js/mlin.js' %}"></script>
</head>
<body>
	<h1>TEMPLATE</h1>
</body>
</html>

Language/Python/Project/django/templates/myapp/test.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>TEST</title>
	<!--
	<link rel="stylesheet" type="text/css" href="/static/myapp/css/style.css"/>
	<script type="text/javascript" src="/static/myapp/js/jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="/static/myapp/js/mlin.js"></script>
	-->
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/style.css' %}"/>
	<script type="text/javascript" src="{% static 'myapp/js/jquery-3.1.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'myapp/js/mlin.js' %}"></script>
</head>
<body>
	<h1>TEST</h1></br>
	{{code}}</br>
	{{code|escape}}</br>
	{{code|safe}}</br>

	{% autoescape off %}
		{{code}}
	{% endautoescape %}
	<!--
	<img src="/static/myapp/img/djangologo.jpg"/>
	-->
	<img src="{% static 'myapp/img/djangologo.jpg' %}"/>
</body>
</html>

Language/Python/Project/django/templates/myapp/upfile.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>UPFILE</title>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/style.css' %}"/>
</head>
<body>
	<h1>UPFILE</h1>
	<form method="post" action="/savefile/" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="file" name="file"/>
		<input type="submit" value="upload"/>
	</form>
</body>
</html>